name: Pull Request Check
on:
  workflow_dispatch:
  pull_request:
    branches:
      - releases/**
    paths:
      - src/**
      - common/**
      - fabric/**
      - forge/**
      - build.gradle
      - gradle.properties
      - settings.gradle

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      ci_version: ${{ steps.properties.outputs.ci_version }}
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Read Properties
        id: 'properties'
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: gradle.properties
          properties: 'ci_version'

  build-20:
    needs: build
    if: ${{ needs.build.outputs.ci_version == '20' }}
    uses: ./.github/workflows/20_pull_request.yml

  build-21:
    needs: build
    if: ${{ needs.build.outputs.ci_version == '21' }}
    uses: ./.github/workflows/21_pull_request.yml
