name: Upload Release Asset
on:
  workflow_dispatch:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      ci_version: ${{ steps.properties.outputs.ci_version }}
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Read Properties
        id: 'properties'
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: gradle.properties
          properties: 'ci_version'

  build-20:
    needs: build
    secrets: inherit
    if: ${{ needs.build.outputs.ci_version == '20' }}
    uses: ./.github/workflows/20_release.yml

  build-21:
    needs: build
    secrets: inherit
    if: ${{ needs.build.outputs.ci_version == '21' }}
    uses: ./.github/workflows/21_release.yml
